FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    sipsak \
    sngrep \
    netbase \
    kamailio \
    kamailio-tls-modules \
    kamailio-extra-modules \
    netbase \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 5060/udp 5060/tcp

CMD ["kamailio", "-DD", "-E", "-f", "/etc/kamailio/kamailio.cfg"]
